### ISSUE TITLE
Missing actionlib

### ISSUE THREAD

**Issue by ryanewel** [aws-robotics/tts-ros1#31]
OS: Ubuntu 16.04
ROS Distro: Kinetic

I tried running this package on the [ros-kinetic-core](https://hub.docker.com/_/ros) docker image. The build succeeded, but when I tried `roslaunch tts sample_application.launch` I got the following error.
```
process[tts_node-4]: started with pid [3611]
Traceback (most recent call last):
  File "/ws/polly_test_ws/install/tts/lib/tts/tts_node.py", line 55, in <module>
    import actionlib
ImportError: No module named actionlib
[tts_node-4] process has died [pid 3611, exit code 1, cmd /ws/polly_test_ws/install/tts/lib/tts/tts_node.py __name:=tts_node __log:=/root/.ros/log/a0521072-be04-11e9-828c-0242ac110002/tts_node-4.log].
log file: /root/.ros/log/a0521072-be04-11e9-828c-0242ac110002/tts_node-4*.log
process[soundplay_node-5]: started with pid [3630]
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/sound_play/soundplay_node.py", line 48, in <module>
    from sound_play.msg import SoundRequest, SoundRequestAction, SoundRequestResult, SoundRequestFeedback
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sound_play/__init__.py", line 33, in <module>
    import libsoundplay as libsoundplay
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sound_play/libsoundplay.py", line 41, in <module>
    import actionlib
ImportError: No module named actionlib
[soundplay_node-5] process has died [pid 3630, exit code 1, cmd /opt/ros/kinetic/lib/sound_play/soundplay_node.py __name:=soundplay_node __log:=/root/.ros/log/a0521072-be04-11e9-828c-0242ac110002/soundplay_node-5.log].
log file: /root/.ros/log/a0521072-be04-11e9-828c-0242ac110002/soundplay_node-5*.log
```
This was solved by adding actionlib as a dependency in the package.xml.

**Comment by ryanewel** [comment]
Issue solved with: https://github.com/aws-robotics/tts-ros1/pull/32
